<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\SecurityEvents */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Security Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="security-events-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'datetime',
            'type',
            'cef_version',
            'cef_severity',
            'cef_event_class_id',
            'cef_device_product',
            'cef_vendor',
            'cef_device_version',
            'cef_name',
            'device_action',
            'application_protocol',
            'device_custom_ipv6_address1',
            'device_custom_ipv6_address1_label',
            'device_custom_ipv6_address2',
            'device_custom_ipv6_address2_label',
            'device_custom_ipv6_address3',
            'device_custom_ipv6_address3_label',
            'device_custom_ipv6_address4',
            'device_custom_ipv6_address4_label',
            'device_event_category',
            'device_customfloating_point1',
            'device_customfloating_point1_label',
            'device_customfloating_point2',
            'device_customfloating_point2_label',
            'device_customfloating_point3',
            'device_customfloating_point3_label',
            'device_customfloating_point4',
            'device_customfloating_point4_label',
            'device_custom_number1',
            'device_custom_number1_label',
            'device_custom_number2',
            'device_custom_number2_label',
            'device_custom_number3',
            'device_custom_number3_label',
            'baseEventCount',
            'device_custom_string1',
            'device_custom_string1_label',
            'device_custom_string2',
            'device_custom_string2_label',
            'device_custom_string3',
            'device_custom_string3_label',
            'device_custom_string4',
            'device_custom_string4_label',
            'device_custom_string5',
            'device_custom_string5_label',
            'device_custom_string6',
            'device_custom_string6_label',
            'device_custom_date1',
            'device_custom_date1_label',
            'device_custom_date2',
            'device_custom_date2_label',
            'device_direction',
            'device_dns_domain',
            'device_external_id',
            'device_facility',
            'device_inbound_interface',
            'device_nt_domain',
            'device_outbound_interface',
            'device_payload_id',
            'device_process_name',
            'device_translated_address',
            'device_time_zone',
            'device_address',
            'device_host_name',
            'device_mac_address',
            'device_process_id ',
            'destination_host_name',
            'destination_mac_address',
            'destination_nt_domain',
            'destination_dns_domain',
            'destination_service_name',
            'destination_translated_address',
            'destination_translated_port',
            'destination_process_id',
            'destination_user_privileges',
            'destination_process_name',
            'destination_port',
            'destination_address',
            'destination_user_id',
            'destination_user_name',
            'destination_group_id',
            'destination_group_name',
            'end_time',
            'external_id',
            'file_create_time',
            'file_hash',
            'file_id',
            'file_modification_time',
            'file_name',
            'file_path',
            'file_permission',
            'file_size',
            'file_type',
            'old_file_create_time',
            'old_file_hash',
            'old_file_id',
            'old_file_modification_time',
            'old_file_name',
            'old_file_path',
            'old_file_permission',
            'old_file_size',
            'old_file_type',
            'flex_date1',
            'flex_date1_label',
            'flex_string1',
            'flex_string1_label',
            'flex_string2',
            'flex_string2_label',
            'bytes_in',
            'bytes_out',
            'message',
            'event_outcome',
            'transport_protocol',
            'reason',
            'request_url:url',
            'request_client_application',
            'request_context',
            'request_cookies',
            'request_method',
            'device_receipt_time',
            'source_host_name',
            'source_mac_address',
            'source_nt_domain',
            'source_dns_domain',
            'source_service_name',
            'source_translated_address',
            'source_translated_port',
            'source_process_id',
            'source_user_privileges',
            'source_process_name',
            'source_port',
            'source_address',
            'source_user_id',
            'source_user_name',
            'source_group_id',
            'source_group_name',
            'start_time',
            'agent_translated_zone_key',
            'agent_zone_key',
            'customer_key',
            'destination_translated_zone_key',
            'destination_zone_key',
            'device_translated_zone_key',
            'device_zone_key',
            'source_translated_zone_key',
            'source_zone_key',
            'reported_duration',
            'reported_resource_group_name',
            'reported_resource_id',
            'reported_resource_name',
            'reported_resource_type',
            'framework_name',
            'threat_actor',
            'threat_attack_id',
            'attack_type',
            'source_country',
            'source_city',
            'destination_country',
            'destination_city',
            'source_geo_longitude',
            'source_geo_latitude',
            'destination_geo_longitude',
            'destination_geo_latitude',
            'destination_ip_network_model',
            'source_ip_network_model',
            'source_code',
            'destination_code',
            'parent_events:ntext',
            'analyzed:boolean',
            'cef_extensions:ntext',
            'raw_event:ntext',
        ],
    ]) ?>

</div>
